using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace UniversalSearchCriteria.Extensions
{
    public static class DataGridExtensions
    {
        // DependencyProperty for the AutoGenerateDateTimeColumns property
        public static readonly DependencyProperty AutoGenerateDateTimeColumnsProperty =
            DependencyProperty.RegisterAttached(
                "AutoGenerateDateTimeColumns",
                typeof(bool),
                typeof(DataGridExtensions),
                new PropertyMetadata(false, OnAutoGenerateDateTimeColumnsChanged));

        // Getter for AutoGenerateDateTimeColumns property
        public static bool GetAutoGenerateDateTimeColumns(DependencyObject obj)
        {
            return (bool)obj.GetValue(AutoGenerateDateTimeColumnsProperty);
        }

        // Setter for AutoGenerateDateTimeColumns property
        public static void SetAutoGenerateDateTimeColumns(DependencyObject obj, bool value)
        {
            obj.SetValue(AutoGenerateDateTimeColumnsProperty, value);
        }

        // Event handler for the AutoGenerateDateTimeColumns property change
        private static void OnAutoGenerateDateTimeColumnsChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is DataGrid dataGrid)
            {
                if ((bool)e.NewValue)
                {
                    // Subscribe to the AutoGeneratingColumn event when the property is set to true
                    dataGrid.AutoGeneratingColumn += DataGrid_AutoGeneratingColumn;
                }
                else
                {
                    // Unsubscribe from the AutoGeneratingColumn event when the property is set to false
                    dataGrid.AutoGeneratingColumn -= DataGrid_AutoGeneratingColumn;
                }
            }
        }

        // Event handler for the AutoGeneratingColumn event
        private static void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyType == typeof(DateTime))
            {
                // Create a new DataGridTextColumn for DateTime properties
                var dateColumn = new DataGridTextColumn();

                // Set the column header to the same as the original column
                dateColumn.Header = e.Column.Header;

                // Set the column's binding to the same as the original column
                dateColumn.Binding = new Binding(e.PropertyName);

                // Apply the desired date format to the binding
                dateColumn.Binding.StringFormat = "dd/MM/yyyy";

                // Replace the original column with the new date column
                e.Column = dateColumn;
            }
        }
    }
}
